run:
    poetry run python tools/ohlc_data_writer.py \
    prediction \
    <'Placeholder Hopsworks API'>\
    ohlc_feature_group\
    2\
    <'place holder for csv file address'>

run-reader:
    poetry run python tools/ohlc_data_reader.py \
    prediction \
    <'placeholder for Hopsworks API>\
    ohlc_feature_group \
    2 \
    ohlc_feature_view \
    1
    
