run:
    poetry run python tools/ohlc_data_writer.py \
    prediction \
    z1QAEGvE0ygHmL2u.GaIDGeO6pUklipx7rmpIRQo3DepqCzG4LUdsNPC8T8YOFJbVyco2fJVLV4SBahoB \
    ohlc_feature_group\
    2\
    <'place holder for csv file address'>

run-reader:
    poetry run python tools/ohlc_data_reader.py \
    prediction \
    <'placeholder for Hopsworks API>\
    ohlc_feature_group \
    2 \
    ohlc_feature_view \
    1
    
