name: trade_producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    multiline: false
    description: The topic where we store trade data
    defaultValue: trade
    required: true
  - name: PRODUCT_IDS
    inputType: FreeText
    multiline: false
    description: list of product_ids we fetch from Kraken
    defaultValue: '["BTC/USD","ETH/EUR","ETH/USD"]'
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
