name: price_predictor
language: python
variables:
  - name: HOPSWORKS_API_KEY
    inputType: Secret
    multiline: false
    defaultValue: HOPSWORKS_API_KEY
    required: true
  - name: HOPSWORKS_PROJECT_NAME
    inputType: Secret
    multiline: false
    defaultValue: HOPSWORKS_PROJECT_NAME
    required: true
  - name: COMET_ML_PROJECT_NAME
    inputType: Secret
    multiline: false
    defaultValue: HOPSWORKS_PROJECT_NAME
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
