name: trade_to_ohlc
language: python
variables:
  - name: KAFKA_INPUT_TOPIC
    inputType: InputTopic
    multiline: false
    description: its an input topic to get trade data
    defaultValue: trade
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
