export HOPSWORKS_PROJECT_NAME=prediction
export PRODUCT_ID=BTC/USD
export FEATURE_GROUP_NAME=ohlc_feature_group
export FEATURE_GROUP_VERSION=2
export FEATURE_VIEW_NAME=ohlc_feature_view
export FEATURE_VIEW_VERSION=1
